server:
  port: 8080

# Actuator + Micrometer
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      tomcat:
        global: true       
        threads: true
        sessions: true
    tags:
      application: stub-app
      environment: docker