spring.profiles.active=default

stub.delay.enabled=true
stub.delay.min=1000
stub.delay.max=2000

spring.datasource.url=jdbc:postgresql://192.168.0.100:5432/testdb
spring.datasource.username=qwe
spring.datasource.password=qwe123